services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres
    expose:
      - "8000"
    volumes:
      - ./media:/app/media
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:stable
    container_name: school_nginx         # renamed so it doesn't conflict with medservise-nginx
    restart: always
    depends_on:
      - backend

    # ðŸ‘‰ SCHOOL PROJECT RUNS ON DIFFERENT PORTS HERE
    ports:
      - "8080:80"      # School project HTTP
      - "8443:443"     # School project HTTPS

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      # STATIC + MEDIA from backend
      - static_volume:/app/staticfiles
      - ./media:/app/media

      # SSL certificates (host-level Certbot)
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

volumes:
  postgres_data:
  static_volume:
